import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format } from 'date-fns';

export async function generateSOAPDF(dealer: any, transactions: any[], dateRange: { from: Date; to: Date }) {
  const doc = new jsPDF('p', 'mm', 'a4');
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 15;
  let currentY = 20;

  // Header Background
  doc.setFillColor(30, 41, 59); // Slate-800
  doc.rect(0, 0, pageWidth, 45, 'F');

  // Title
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('STATEMENT OF ACCOUNT', margin, 25);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Period: ${format(dateRange.from, 'dd MMM yyyy')} to ${format(dateRange.to, 'dd MMM yyyy')}`, margin, 35);
  doc.text(`Generated on: ${format(new Date(), 'dd/MM/yyyy HH:mm')}`, margin, 40);

  currentY = 60;
  
  // Dealer Info Section
  doc.setTextColor(30, 41, 59);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('STATEMENT FOR:', margin, currentY);
  currentY += 7;
  
  doc.setFontSize(14);
  doc.text(dealer.name?.toUpperCase() || 'DEALER NAME', margin, currentY);
  currentY += 6;
  
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  const addrLines = doc.splitTextToSize(dealer.address || 'Address not available', 100);
  doc.text(addrLines, margin, currentY);
  
  // Right side info (Balance summary)
  const totalDebit = transactions.reduce((sum, t) => sum + (t.debit || 0), 0);
  const totalCredit = transactions.reduce((sum, t) => sum + (t.credit || 0), 0);
  const closingBalance = transactions[transactions.length - 1]?.balance || 0;

  let infoX = pageWidth - margin - 60;
  let infoY = 60;
  doc.setFont('helvetica', 'bold');
  doc.text('SUMMARY', infoX, infoY);
  doc.line(infoX, infoY + 2, pageWidth - margin, infoY + 2);
  
  infoY += 8;
  doc.setFont('helvetica', 'normal');
  doc.text('Total Debit:', infoX, infoY);
  doc.text(totalDebit.toLocaleString('en-IN', { minimumFractionDigits: 2 }), pageWidth - margin, infoY, { align: 'right' });
  
  infoY += 5;
  doc.text('Total Credit:', infoX, infoY);
  doc.text(totalCredit.toLocaleString('en-IN', { minimumFractionDigits: 2 }), pageWidth - margin, infoY, { align: 'right' });
  
  infoY += 7;
  doc.setFont('helvetica', 'bold');
  doc.setFillColor(248, 250, 252);
  doc.rect(infoX - 2, infoY - 4, 64, 8, 'F');
  doc.text('Closing Balance:', infoX, infoY + 1);
  doc.text(closingBalance.toLocaleString('en-IN', { minimumFractionDigits: 2 }), pageWidth - margin, infoY + 1, { align: 'right' });

  currentY = Math.max(currentY + (addrLines.length * 5), infoY + 15);

  // Transactions Table
  autoTable(doc, {
    startY: currentY,
    head: [['Date', 'Particulars', 'Voucher Type', 'Ref No', 'Debit', 'Credit', 'Balance']],
    body: transactions.map(t => [
      format(new Date(t.date), 'dd/MM/yyyy'),
      t.particulars || '',
      t.voucherType || '',
      t.voucherNo || t.refNo || '',
      t.debit ? t.debit.toFixed(2) : '-',
      t.credit ? t.credit.toFixed(2) : '-',
      t.balance ? t.balance.toFixed(2) : '0.00'
    ]),
    theme: 'grid',
    headStyles: { fillColor: [30, 41, 59], textColor: [255, 255, 255], fontSize: 8, fontStyle: 'bold' },
    bodyStyles: { fontSize: 8, textColor: [51, 65, 85] },
    columnStyles: {
      0: { cellWidth: 20 },
      1: { cellWidth: 'auto' },
      4: { halign: 'right', cellWidth: 25 },
      5: { halign: 'right', cellWidth: 25 },
      6: { halign: 'right', cellWidth: 25 }
    },
    alternateRowStyles: { fillColor: [248, 250, 252] }
  });

  // Footer
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text(
      `Page ${i} of ${pageCount} | Generated by FreightFlow Digital System`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
  }

  return doc;
}
